# Generated by Django 3.2.15 on 2022-08-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_col', models.IntegerField()),
                ('character_col', models.CharField(max_length=100)),
                ('date_col', models.DateField()),
                ('datetime_col', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModelWithForeignKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.testmodel')),
            ],
        ),
    ]
